Repository vuejs/docs-next-zh-cn, pull requests merged in 2020-11, with the labels that each got.

#252 docs: update translation for guide/contributing/translations
  src/guide/contributing/translations.md
Labels: 校对

#250 docs: routing.md
  src/guide/routing.md
Labels: 校对

#258 docs: update component-slots.md
  src/guide/component-slots.md
Labels: 代码修改 (建议直接提到英文站，我们会定期从英文站同步改动)

#293 docs: src/guide/migration/children.md
  src/guide/migration/children.md
Labels: 翻译
