Repository vuejs/docs-next-zh-cn, pull requests merged in 2020-09, with the labels that each got.

#34 docs: translate partners
  src/community/partners.md
Labels: 翻译

#29 Review testing.md
  src/guide/testing.md
Labels: 校对

#41 Review testing.md
  src/guide/testing.md
Labels: 校对

#38 fix: modified the translation of sentence
  src/guide/component-edge-cases.md
  src/guide/component-template-refs.md
  src/guide/custom-directive.md
  src/guide/render-function.md
  src/guide/teleport.md
  src/guide/transitions-enterleave.md
  src/guide/transitions-overview.md
Labels: 校对

#39 fix: modified the translation of sentence in v-model.md file
  src/guide/migration/v-model.md
Labels: 校对

#57 docs: translate render function, config.js
  src/.vuepress/config.js
  src/api/options-composition.md
  src/guide/component-edge-cases.md
  src/guide/composition-api-setup.md
  src/guide/migration/render-function-api.md
  src/guide/migration/slots-unification.md
  src/guide/reactivity.md
  src/guide/render-function.md
Labels: 校对

#25 Complete translation of editable-svg-icons.md
  src/cookbook/editable-svg-icons.md
Labels: 翻译

#22 review reactiveity.md and reactivity-fundamentals.md and change some content
  src/guide/reactivity-fundamentals.md
  src/guide/reactivity.md
Labels: 校对

#60 docs: src/cookbook/index.md first commit
  src/cookbook/index.md
Labels: 翻译

#90 Review composition-api-setup.md
  src/guide/composition-api-setup.md
Labels: 校对

#94 docs: src/guide/migration/props-default-this.md
  src/guide/migration/props-default-this.md
Labels: 翻译

#92 docs: src/guide/migration/v-bind.md
  src/guide/migration/v-bind.md
Labels: 翻译

#108 docs: review-src-api-global-api.md (#80)
  src/api/global-api.md
Labels: 校对

#146 update-template-refs
  src/guide/composition-api-template-refs.md
Labels: 校对

#156 feat: support docsearch
  src/.vuepress/config.js
  src/.vuepress/theme/components/Navbar.vue
Labels: 网络环境和本地化
