Repository vuejs/docs-next-zh-cn, pull requests merged in 2020-10, with the labels that each got.

#163 sync: #26964a5
  .github/pull_request_template.md
  assets/transitions-diagram.ai.zip
  package.json
  src/.vuepress/components/AppBanner.vue
  src/.vuepress/components/common/vuemastery-video-modal.vue
  src/.vuepress/config.js
  src/.vuepress/public/images/transitions.svg
  src/.vuepress/theme/components/Navbar.vue
  src/.vuepress/theme/layouts/Layout.vue
  src/.vuepress/theme/package.json
  src/guide/migration/watch.md
  src/guide/mobile.md
  src/search/README.md
  yarn.lock
Labels: 从英文版同步

#182 docs: style-guide/README.md
  src/style-guide/README.md
Labels: 校对

#203 style: Unified style
  src/guide/migration/custom-directives.md
  src/guide/migration/custom-elements-interop.md
  src/guide/migration/fragments.md
Labels: 校对

#205 Update introduction.md
  src/guide/introduction.md
Labels: 翻译讨论

#201 docs: src/guide/data-methods.md
  src/guide/data-methods.md
Labels: 翻译
