Repository vuejs/docs-next-zh-cn, pull requests merged in 2021-11, with the labels that each got.

#806 sync #c90a0a2
  src/.vuepress/components/community/team/partners.js
  src/api/directives.md
  src/api/sfc-script-setup.md
  src/guide/component-basics.md
  src/guide/component-props.md
  src/guide/component-registration.md
  src/guide/component-slots.md
  src/guide/forms.md
  src/guide/single-file-component.md
Labels: 从英文版同步

#808 translate todos
  src/api/built-in-components.md
  src/api/sfc-script-setup.md
  src/guide/component-basics.md
  src/guide/component-props.md
  src/guide/component-registration.md
  src/guide/component-slots.md
  src/guide/forms.md
  src/guide/single-file-component.md
Labels: 翻译

#796 update routing.md
  src/guide/ssr/routing.md
Labels: 校对

#810 update component-attrs.md
  src/guide/component-attrs.md
Labels: 校对

#797 Update template-syntax.md
  src/guide/template-syntax.md
Labels: 校对

#798 Update data-methods.md
  src/guide/data-methods.md
Labels: 校对

#800 Update class-and-style.md
  src/guide/class-and-style.md
Labels: 校对

#799 Update computed.md
  src/guide/computed.md
Labels: 校对

#801 Update conditional.md
  src/guide/conditional.md
Labels: 校对

#802 Update list.md
  src/guide/list.md
Labels: 校对

#803 Update events.md
  src/guide/events.md
Labels: 校对

#804 Update forms.md
  src/guide/forms.md
Labels: 校对

#805 Update component-basics.md
  src/guide/component-basics.md
Labels: 校对

#809 update component-props.md
  src/guide/component-props.md
Labels: 校对

#786 hydration -> 激活
  src/guide/ssr/getting-started.md
  src/guide/ssr/hydration.md
  src/guide/ssr/introduction.md
  src/guide/ssr/structure.md
Labels: 翻译, 校对

#814 update component-custom-events.md
  src/guide/component-custom-events.md
Labels: 校对

#816 update component-provide-inject.md
  src/guide/component-provide-inject.md
Labels: 校对

#818 update component-template-refs.md
  src/guide/component-template-refs.md
Labels: 校对

#820 Update computed.md. fix translation
  src/guide/computed.md
Labels: 校对

#821 sync #b596073
  src/api/sfc-script-setup.md
  src/guide/component-attrs.md
  src/guide/component-slots.md
  src/guide/installation.md
  src/style-guide/README.md
Labels: 从英文版同步

#815 update component-slots.md
  src/guide/component-slots.md
Labels: 校对

#817 update component-dynamic-async.md
  src/guide/component-dynamic-async.md
Labels: 校对

#819 update component-edge-cases.md
  src/guide/component-edge-cases.md
Labels: 校对

#826 Update directives.md
  src/api/directives.md
Labels: 翻译
