Repository vuejs/docs-next-zh-cn, pull requests merged in 2021-03, with the labels that each got.

#386 sync: #efbbe59
  assets/lifecycle-diagram.svg
  assets/scoped-slot-diagram.svg
  assets/slot-render-diagram.svg
  package.json
  src/.vuepress/components/support/Coins.vue
  src/.vuepress/config.js
  src/.vuepress/public/images/coin-bch.png
  src/.vuepress/public/images/coin-btc.png
  src/.vuepress/public/images/coin-eth.png
  src/.vuepress/public/images/coin-ltc.png
  src/.vuepress/public/images/lifecycle.png
  src/.vuepress/public/images/lifecycle.svg
  src/.vuepress/theme/components/BuySellAds.vue
  src/.vuepress/theme/components/CarbonAds.vue
  src/.vuepress/theme/components/Home.vue
  src/.vuepress/theme/layouts/Layout.vue
  src/.vuepress/theme/package.json
  src/.vuepress/theme/styles/index.styl
  src/api/application-api.md
  src/api/application-config.md
  src/api/basic-reactivity.md
  src/api/built-in-components.md
  src/api/global-api.md
  src/api/instance-methods.md
  src/api/instance-properties.md
  src/api/options-lifecycle-hooks.md
  src/api/refs-api.md
  src/cookbook/debugging-in-vscode.md
  src/guide/class-and-style.md
  src/guide/component-basics.md
  src/guide/component-custom-events.md
  src/guide/component-dynamic-async.md
  src/guide/component-slots.md
  src/guide/composition-api-template-refs.md
  src/guide/events.md
  src/guide/forms.md
  src/guide/instance.md
  src/guide/list.md
  src/guide/migration/array-refs.md
  src/guide/migration/custom-directives.md
  src/guide/migration/functional-components.md
  src/guide/migration/global-api.md
  src/guide/migration/inline-template-attribute.md
  src/guide/migration/v-if-v-for.md
  src/guide/reactivity-computed-watchers.md
  src/guide/routing.md
  src/guide/single-file-component.md
  src/guide/state-management.md
  src/guide/template-syntax.md
  src/guide/transitions-enterleave.md
  src/guide/transitions-list.md
  src/guide/typescript-support.md
Labels: 从英文版同步

#428 docs: component-dynamic-async.md
  src/guide/component-dynamic-async.md
Labels: 校对

#395 docs: proofread src/guide/migration/slots-unification.md
  src/guide/migration/render-function-api.md
  src/guide/migration/slots-unification.md
Labels: 翻译讨论

#440 docs: keycode-modifiers.md
  src/guide/migration/keycode-modifiers.md
Labels: 校对
